import ServiceOverview from '@/components/reusable/ServiceOverview';
import { getServices } from '@/server/service.service';
import React from 'react';

export const metadata = {
  title: "Services | Care Io",
  description: "Generated by create next app",
};


const Service = async () => {
    const services = await getServices();
    return (
        <div>
            <ServiceOverview services={services} />
        </div>
    );
};

export default Service;