export const dynamic = "force-dynamic";
import { myReviews } from "@/server/review.service";
import React from "react";
import ReviewManager from "./_components/ReviewManager";

export const metadata = {
  title: "Reviews | Dashboard",
  description: "Generated by create next app",
};

const page = async () => {
  const result = await myReviews();
  const reviews = JSON.parse(JSON.stringify(result.data));
  return (
    <>
      <ReviewManager reviews={reviews} />
    </>
  );
};

export default page;
