import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const poppins = Poppins(
  {
    weight: ["100", "300", "400", "500", "600", "800"]
  }
) 

export const metadata = {
  title: "Care.io",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}`}
      >
        <header><Navbar></Navbar></header>
        <main>
          {children}
        </main>
        <footer><Footer></Footer></footer>
      </body>
    </html>
  );
}
