import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";
import SmoothScroll from "@/components/styles/SmoothScroll";
import ScrollToTop from "@/components/styles/ScrollToTop";

const poppins = Poppins(
  {
    weight: ["100", "300", "400", "500", "600", "800"]
  }
) 

export const metadata = {
  title:{
    default: "Care.io",
    template: "%s" | "Care.io"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <script
            dangerouslySetInnerHTML={{
              __html: `
              (function () {
                try {
                  const saved = localStorage.getItem("theme");

                  if (saved) {
                    document.documentElement.setAttribute("data-theme", saved);
                  } else {
                    const systemDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
                    document.documentElement.setAttribute("data-theme", systemDark ? "dark" : "light");
                  }
                } catch (e) {}
              })();
            `,
            }}
          />
        </head>

        <body className={`${poppins.className}`}>
          <SmoothScroll>
            <header>
              <Navbar />
            </header>

            <main>
              {children}
              <ScrollToTop/>
            </main>

            <footer>
              <Footer />
            </footer>

          </SmoothScroll>
        </body>
      </html>
    </NextAuthProvider>
  );
}
