import Navbar from "@/components/HomeLayout/components/Navbar";
import Footer from "@/components/HomeLayout/components/Footer";

export const metadata = {
  title: "Home ",
  description: "Generated by create next app",
}

export default function HomeLayout({ children }) {
  return (
    <>
      <Navbar />

      <main>
        {children}
      </main>

      <Footer />
    </>
  );
}