import React from 'react';

export const metadata = {
  title: "Payment | Dashboard",
  description: "Generated by create next app",
};


const page = () => {
    return (
        <div>
            this is payment history
        </div>
    );
};

export default page;